# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analog_clock_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalogClock(object):
    def setupUi(self, AnalogClock):
        AnalogClock.setObjectName("AnalogClock")
        AnalogClock.resize(1080, 720)
        AnalogClock.setStyleSheet("QWidget{\n"
"    background-color: rgb(12, 95, 112);\n"
"}")
        self.button_x1 = QtWidgets.QPushButton(AnalogClock)
        self.button_x1.setGeometry(QtCore.QRect(850, 210, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x1.setFont(font)
        self.button_x1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x1.setObjectName("button_x1")
        self.button_x2 = QtWidgets.QPushButton(AnalogClock)
        self.button_x2.setGeometry(QtCore.QRect(850, 340, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x2.setFont(font)
        self.button_x2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x2.setObjectName("button_x2")
        self.button_x4 = QtWidgets.QPushButton(AnalogClock)
        self.button_x4.setGeometry(QtCore.QRect(850, 460, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x4.setFont(font)
        self.button_x4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x4.setObjectName("button_x4")
        self.button_x05 = QtWidgets.QPushButton(AnalogClock)
        self.button_x05.setGeometry(QtCore.QRect(850, 580, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x05.setFont(font)
        self.button_x05.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x05.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x05.setObjectName("button_x05")
        self.button_x025 = QtWidgets.QPushButton(AnalogClock)
        self.button_x025.setGeometry(QtCore.QRect(850, 100, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x025.setFont(font)
        self.button_x025.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x025.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x025.setObjectName("button_x025")
        self.edit_time = QtWidgets.QTimeEdit(AnalogClock)
        self.edit_time.setGeometry(QtCore.QRect(40, 660, 120, 25))
        self.edit_time.setStyleSheet("QTimeEdit{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.edit_time.setTime(QtCore.QTime(12, 59, 59))
        self.edit_time.setObjectName("edit_time")
        self.button_setTime = QtWidgets.QPushButton(AnalogClock)
        self.button_setTime.setGeometry(QtCore.QRect(190, 660, 40, 25))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.button_setTime.setFont(font)
        self.button_setTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_setTime.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_setTime.setObjectName("button_setTime")
        self.button_setCurrentTime = QtWidgets.QPushButton(AnalogClock)
        self.button_setCurrentTime.setGeometry(QtCore.QRect(260, 660, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.button_setCurrentTime.setFont(font)
        self.button_setCurrentTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_setCurrentTime.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_setCurrentTime.setObjectName("button_setCurrentTime")

        self.retranslateUi(AnalogClock)
        QtCore.QMetaObject.connectSlotsByName(AnalogClock)

    def retranslateUi(self, AnalogClock):
        _translate = QtCore.QCoreApplication.translate
        AnalogClock.setWindowTitle(_translate("AnalogClock", "Form"))
        self.button_x1.setText(_translate("AnalogClock", "x1"))
        self.button_x2.setText(_translate("AnalogClock", "x2"))
        self.button_x4.setText(_translate("AnalogClock", "x4"))
        self.button_x05.setText(_translate("AnalogClock", "x0.5"))
        self.button_x025.setText(_translate("AnalogClock", "x0.25"))
        self.edit_time.setDisplayFormat(_translate("AnalogClock", "HH:mm:ss"))
        self.button_setTime.setText(_translate("AnalogClock", "set"))
        self.button_setCurrentTime.setText(_translate("AnalogClock", "current time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnalogClock = QtWidgets.QWidget()
    ui = Ui_AnalogClock()
    ui.setupUi(AnalogClock)
    AnalogClock.show()
    sys.exit(app.exec_())
