# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digital_clock_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DigitalClock(object):
    def setupUi(self, DigitalClock):
        DigitalClock.setObjectName("DigitalClock")
        DigitalClock.resize(1080, 720)
        DigitalClock.setStyleSheet("QWidget{\n"
"    background-color: rgb(12, 95, 112);\n"
"}")
        self.widget = QtWidgets.QWidget(DigitalClock)
        self.widget.setGeometry(QtCore.QRect(215, 280, 621, 155))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(54, 21, 161);\n"
"    border-radius: 10px;\n"
"}")
        self.widget.setObjectName("widget")
        self.widget_hour_1 = QtWidgets.QWidget(self.widget)
        self.widget_hour_1.setGeometry(QtCore.QRect(12, 10, 70, 135))
        self.widget_hour_1.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_hour_1.setObjectName("widget_hour_1")
        self.pixmap_hour_2 = QtWidgets.QLabel(self.widget_hour_1)
        self.pixmap_hour_2.setGeometry(QtCore.QRect(0, 0, 70, 135))
        self.pixmap_hour_2.setText("")
        self.pixmap_hour_2.setObjectName("pixmap_hour_2")
        self.widget_hour_2 = QtWidgets.QWidget(self.widget)
        self.widget_hour_2.setGeometry(QtCore.QRect(108, 10, 70, 135))
        self.widget_hour_2.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_hour_2.setObjectName("widget_hour_2")
        self.pixmap_hour_1 = QtWidgets.QLabel(self.widget_hour_2)
        self.pixmap_hour_1.setGeometry(QtCore.QRect(0, 0, 70, 135))
        self.pixmap_hour_1.setText("")
        self.pixmap_hour_1.setObjectName("pixmap_hour_1")
        self.widget_minute_2 = QtWidgets.QWidget(self.widget)
        self.widget_minute_2.setGeometry(QtCore.QRect(323, 10, 70, 135))
        self.widget_minute_2.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_minute_2.setObjectName("widget_minute_2")
        self.pixmap_minute_1 = QtWidgets.QLabel(self.widget_minute_2)
        self.pixmap_minute_1.setGeometry(QtCore.QRect(0, 0, 70, 135))
        self.pixmap_minute_1.setText("")
        self.pixmap_minute_1.setObjectName("pixmap_minute_1")
        self.widget_second_1 = QtWidgets.QWidget(self.widget)
        self.widget_second_1.setGeometry(QtCore.QRect(444, 10, 70, 135))
        self.widget_second_1.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_second_1.setObjectName("widget_second_1")
        self.pixmap_second_2 = QtWidgets.QLabel(self.widget_second_1)
        self.pixmap_second_2.setGeometry(QtCore.QRect(0, 0, 70, 135))
        self.pixmap_second_2.setText("")
        self.pixmap_second_2.setObjectName("pixmap_second_2")
        self.widget_second_2 = QtWidgets.QWidget(self.widget)
        self.widget_second_2.setGeometry(QtCore.QRect(540, 10, 70, 135))
        self.widget_second_2.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_second_2.setObjectName("widget_second_2")
        self.pixmap_second_1 = QtWidgets.QLabel(self.widget_second_2)
        self.pixmap_second_1.setGeometry(QtCore.QRect(0, 0, 70, 135))
        self.pixmap_second_1.setText("")
        self.pixmap_second_1.setObjectName("pixmap_second_1")
        self.widget_minute_1 = QtWidgets.QWidget(self.widget)
        self.widget_minute_1.setGeometry(QtCore.QRect(228, 10, 70, 135))
        self.widget_minute_1.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_minute_1.setObjectName("widget_minute_1")
        self.pixmap_minute_2 = QtWidgets.QLabel(self.widget_minute_1)
        self.pixmap_minute_2.setGeometry(QtCore.QRect(0, 0, 70, 135))
        self.pixmap_minute_2.setText("")
        self.pixmap_minute_2.setObjectName("pixmap_minute_2")
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setGeometry(QtCore.QRect(193, 40, 20, 20))
        self.widget_8.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.widget_9 = QtWidgets.QWidget(self.widget)
        self.widget_9.setGeometry(QtCore.QRect(193, 90, 20, 20))
        self.widget_9.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.widget)
        self.widget_10.setGeometry(QtCore.QRect(408, 40, 20, 20))
        self.widget_10.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.widget)
        self.widget_11.setGeometry(QtCore.QRect(408, 90, 20, 20))
        self.widget_11.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(255, 3, 58);\n"
"}")
        self.widget_11.setObjectName("widget_11")
        self.button_x025 = QtWidgets.QPushButton(DigitalClock)
        self.button_x025.setGeometry(QtCore.QRect(100, 620, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x025.setFont(font)
        self.button_x025.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x025.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x025.setObjectName("button_x025")
        self.button_x1 = QtWidgets.QPushButton(DigitalClock)
        self.button_x1.setGeometry(QtCore.QRect(300, 620, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x1.setFont(font)
        self.button_x1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x1.setObjectName("button_x1")
        self.button_x2 = QtWidgets.QPushButton(DigitalClock)
        self.button_x2.setGeometry(QtCore.QRect(500, 620, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x2.setFont(font)
        self.button_x2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x2.setObjectName("button_x2")
        self.button_x4 = QtWidgets.QPushButton(DigitalClock)
        self.button_x4.setGeometry(QtCore.QRect(700, 620, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x4.setFont(font)
        self.button_x4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x4.setObjectName("button_x4")
        self.button_x05 = QtWidgets.QPushButton(DigitalClock)
        self.button_x05.setGeometry(QtCore.QRect(900, 620, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.button_x05.setFont(font)
        self.button_x05.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_x05.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_x05.setObjectName("button_x05")
        self.edit_time = QtWidgets.QTimeEdit(DigitalClock)
        self.edit_time.setGeometry(QtCore.QRect(920, 40, 120, 25))
        self.edit_time.setStyleSheet("QTimeEdit{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.edit_time.setTime(QtCore.QTime(12, 59, 59))
        self.edit_time.setObjectName("edit_time")
        self.button_setTime = QtWidgets.QPushButton(DigitalClock)
        self.button_setTime.setGeometry(QtCore.QRect(850, 40, 40, 25))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.button_setTime.setFont(font)
        self.button_setTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_setTime.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_setTime.setObjectName("button_setTime")
        self.button_setCurrentTime = QtWidgets.QPushButton(DigitalClock)
        self.button_setCurrentTime.setGeometry(QtCore.QRect(710, 40, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.button_setCurrentTime.setFont(font)
        self.button_setCurrentTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_setCurrentTime.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_setCurrentTime.setObjectName("button_setCurrentTime")

        self.retranslateUi(DigitalClock)
        QtCore.QMetaObject.connectSlotsByName(DigitalClock)

    def retranslateUi(self, DigitalClock):
        _translate = QtCore.QCoreApplication.translate
        DigitalClock.setWindowTitle(_translate("DigitalClock", "Form"))
        self.button_x025.setText(_translate("DigitalClock", "x0.25"))
        self.button_x1.setText(_translate("DigitalClock", "x1"))
        self.button_x2.setText(_translate("DigitalClock", "x2"))
        self.button_x4.setText(_translate("DigitalClock", "x4"))
        self.button_x05.setText(_translate("DigitalClock", "x0.5"))
        self.edit_time.setDisplayFormat(_translate("DigitalClock", "HH:mm:ss"))
        self.button_setTime.setText(_translate("DigitalClock", "set"))
        self.button_setCurrentTime.setText(_translate("DigitalClock", "current time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DigitalClock = QtWidgets.QWidget()
    ui = Ui_DigitalClock()
    ui.setupUi(DigitalClock)
    DigitalClock.show()
    sys.exit(app.exec_())
