# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(1080, 720)
        MainMenu.setAutoFillBackground(False)
        MainMenu.setStyleSheet("QWidget{\n"
"    background-color: rgb(12, 95, 112);\n"
"}")
        self.button_analog = QtWidgets.QPushButton(MainMenu)
        self.button_analog.setGeometry(QtCore.QRect(260, 320, 200, 140))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_analog.setFont(font)
        self.button_analog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_analog.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_analog.setObjectName("button_analog")
        self.label_clock_menu = QtWidgets.QLabel(MainMenu)
        self.label_clock_menu.setGeometry(QtCore.QRect(340, 100, 391, 100))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_clock_menu.setFont(font)
        self.label_clock_menu.setTextFormat(QtCore.Qt.AutoText)
        self.label_clock_menu.setObjectName("label_clock_menu")
        self.button_digital = QtWidgets.QPushButton(MainMenu)
        self.button_digital.setGeometry(QtCore.QRect(600, 320, 200, 140))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_digital.setFont(font)
        self.button_digital.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_digital.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_digital.setStyleSheet("QPushButton{\n"
"    background-color: rgb(11, 159, 182);\n"
"}")
        self.button_digital.setObjectName("button_digital")

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Form"))
        self.button_analog.setText(_translate("MainMenu", "Analog Clock"))
        self.label_clock_menu.setText(_translate("MainMenu", "CLOCK MENU"))
        self.button_digital.setText(_translate("MainMenu", "Digital clock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QWidget()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())
